dir: "{{.InterfaceDir}}/mocks"
filename: "{{.InterfaceName}}.go"
pkgname: "{{.SrcPackageName}}mocks"
packages:
  github.com/jadechy/barterswap/internal/offer:
    interfaces:
      Repository:
  github.com/jadechy/barterswap/internal/user:
    interfaces:
      Repository:
  github.com/jadechy/barterswap/internal/dbx:
    interfaces:
      TxRunner:
  github.com/jadechy/barterswap/internal/exchange:
    interfaces:
      Repository:
      OfferGetter:
      UserGetter:
      CreditLedger:
  github.com/jadechy/barterswap/internal/review:
    interfaces:
      Repository:
      ExchangeGetter:
