services:
  go:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/home/go
      - go-mod-cache:/go
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    image: mysql:8.0
    platform: linux/x86_64
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "go",
          "-ppassword",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db-data:
  go-mod-cache:
