// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package exchange

import (
	"context"

	"github.com/jadechy/barterswap/internal/dbx"
	"github.com/jadechy/barterswap/internal/offer"
	"github.com/jadechy/barterswap/internal/user"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, e *Exchange) error {
	ret := _mock.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Exchange) error); ok {
		r0 = returnFunc(ctx, e)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - e *Exchange
func (_e *MockRepository_Expecter) Create(ctx any, e any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, e)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, e *Exchange)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Exchange
		if args[1] != nil {
			arg1 = args[1].(*Exchange)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(err error) *MockRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, e *Exchange) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByID(ctx context.Context, id int) (Exchange, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 Exchange
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (Exchange, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) Exchange); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(Exchange)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockRepository_Expecter) GetByID(ctx any, id any) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(exchange Exchange, err error) *MockRepository_GetByID_Call {
	_c.Call.Return(exchange, err)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (Exchange, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// HasActive provides a mock function for the type MockRepository
func (_mock *MockRepository) HasActive(ctx context.Context, serviceID int) (bool, error) {
	ret := _mock.Called(ctx, serviceID)

	if len(ret) == 0 {
		panic("no return value specified for HasActive")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (bool, error)); ok {
		return returnFunc(ctx, serviceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) bool); ok {
		r0 = returnFunc(ctx, serviceID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, serviceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_HasActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasActive'
type MockRepository_HasActive_Call struct {
	*mock.Call
}

// HasActive is a helper method to define mock.On call
//   - ctx context.Context
//   - serviceID int
func (_e *MockRepository_Expecter) HasActive(ctx any, serviceID any) *MockRepository_HasActive_Call {
	return &MockRepository_HasActive_Call{Call: _e.mock.On("HasActive", ctx, serviceID)}
}

func (_c *MockRepository_HasActive_Call) Run(run func(ctx context.Context, serviceID int)) *MockRepository_HasActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_HasActive_Call) Return(b bool, err error) *MockRepository_HasActive_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_HasActive_Call) RunAndReturn(run func(ctx context.Context, serviceID int) (bool, error)) *MockRepository_HasActive_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRepository
func (_mock *MockRepository) List(ctx context.Context, userID int, status string) ([]Exchange, error) {
	ret := _mock.Called(ctx, userID, status)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []Exchange
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) ([]Exchange, error)); ok {
		return returnFunc(ctx, userID, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) []Exchange); ok {
		r0 = returnFunc(ctx, userID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Exchange)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = returnFunc(ctx, userID, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - status string
func (_e *MockRepository_Expecter) List(ctx any, userID any, status any) *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List", ctx, userID, status)}
}

func (_c *MockRepository_List_Call) Run(run func(ctx context.Context, userID int, status string)) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(exchanges []Exchange, err error) *MockRepository_List_Call {
	_c.Call.Return(exchanges, err)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func(ctx context.Context, userID int, status string) ([]Exchange, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateStatus(ctx context.Context, q dbx.Querier, id int, status string) error {
	ret := _mock.Called(ctx, q, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dbx.Querier, int, string) error); ok {
		r0 = returnFunc(ctx, q, id, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - q dbx.Querier
//   - id int
//   - status string
func (_e *MockRepository_Expecter) UpdateStatus(ctx any, q any, id any, status any) *MockRepository_UpdateStatus_Call {
	return &MockRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, q, id, status)}
}

func (_c *MockRepository_UpdateStatus_Call) Run(run func(ctx context.Context, q dbx.Querier, id int, status string)) *MockRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dbx.Querier
		if args[1] != nil {
			arg1 = args[1].(dbx.Querier)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateStatus_Call) Return(err error) *MockRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, q dbx.Querier, id int, status string) error) *MockRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOfferGetter creates a new instance of MockOfferGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOfferGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOfferGetter {
	mock := &MockOfferGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOfferGetter is an autogenerated mock type for the OfferGetter type
type MockOfferGetter struct {
	mock.Mock
}

type MockOfferGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOfferGetter) EXPECT() *MockOfferGetter_Expecter {
	return &MockOfferGetter_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockOfferGetter
func (_mock *MockOfferGetter) GetByID(ctx context.Context, id int) (offer.Offer, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 offer.Offer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (offer.Offer, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) offer.Offer); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(offer.Offer)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOfferGetter_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockOfferGetter_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockOfferGetter_Expecter) GetByID(ctx any, id any) *MockOfferGetter_GetByID_Call {
	return &MockOfferGetter_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockOfferGetter_GetByID_Call) Run(run func(ctx context.Context, id int)) *MockOfferGetter_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOfferGetter_GetByID_Call) Return(offer1 offer.Offer, err error) *MockOfferGetter_GetByID_Call {
	_c.Call.Return(offer1, err)
	return _c
}

func (_c *MockOfferGetter_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (offer.Offer, error)) *MockOfferGetter_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserGetter creates a new instance of MockUserGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserGetter {
	mock := &MockUserGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserGetter is an autogenerated mock type for the UserGetter type
type MockUserGetter struct {
	mock.Mock
}

type MockUserGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserGetter) EXPECT() *MockUserGetter_Expecter {
	return &MockUserGetter_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockUserGetter
func (_mock *MockUserGetter) GetByID(ctx context.Context, id int) (user.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (user.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) user.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(user.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserGetter_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserGetter_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockUserGetter_Expecter) GetByID(ctx any, id any) *MockUserGetter_GetByID_Call {
	return &MockUserGetter_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockUserGetter_GetByID_Call) Run(run func(ctx context.Context, id int)) *MockUserGetter_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserGetter_GetByID_Call) Return(user1 user.User, err error) *MockUserGetter_GetByID_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserGetter_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (user.User, error)) *MockUserGetter_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreditLedger creates a new instance of MockCreditLedger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreditLedger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreditLedger {
	mock := &MockCreditLedger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreditLedger is an autogenerated mock type for the CreditLedger type
type MockCreditLedger struct {
	mock.Mock
}

type MockCreditLedger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreditLedger) EXPECT() *MockCreditLedger_Expecter {
	return &MockCreditLedger_Expecter{mock: &_m.Mock}
}

// AddCreditTransaction provides a mock function for the type MockCreditLedger
func (_mock *MockCreditLedger) AddCreditTransaction(ctx context.Context, q dbx.Querier, userID int, exchangeID *int, montant int, typ string) error {
	ret := _mock.Called(ctx, q, userID, exchangeID, montant, typ)

	if len(ret) == 0 {
		panic("no return value specified for AddCreditTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dbx.Querier, int, *int, int, string) error); ok {
		r0 = returnFunc(ctx, q, userID, exchangeID, montant, typ)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCreditLedger_AddCreditTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCreditTransaction'
type MockCreditLedger_AddCreditTransaction_Call struct {
	*mock.Call
}

// AddCreditTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - q dbx.Querier
//   - userID int
//   - exchangeID *int
//   - montant int
//   - typ string
func (_e *MockCreditLedger_Expecter) AddCreditTransaction(ctx any, q any, userID any, exchangeID any, montant any, typ any) *MockCreditLedger_AddCreditTransaction_Call {
	return &MockCreditLedger_AddCreditTransaction_Call{Call: _e.mock.On("AddCreditTransaction", ctx, q, userID, exchangeID, montant, typ)}
}

func (_c *MockCreditLedger_AddCreditTransaction_Call) Run(run func(ctx context.Context, q dbx.Querier, userID int, exchangeID *int, montant int, typ string)) *MockCreditLedger_AddCreditTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dbx.Querier
		if args[1] != nil {
			arg1 = args[1].(dbx.Querier)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *int
		if args[3] != nil {
			arg3 = args[3].(*int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockCreditLedger_AddCreditTransaction_Call) Return(err error) *MockCreditLedger_AddCreditTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCreditLedger_AddCreditTransaction_Call) RunAndReturn(run func(ctx context.Context, q dbx.Querier, userID int, exchangeID *int, montant int, typ string) error) *MockCreditLedger_AddCreditTransaction_Call {
	_c.Call.Return(run)
	return _c
}
