// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usermocks

import (
	"context"

	"github.com/jadechy/barterswap/internal/dbx"
	"github.com/jadechy/barterswap/internal/user"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AddCreditTransaction provides a mock function for the type MockRepository
func (_mock *MockRepository) AddCreditTransaction(ctx context.Context, q dbx.Querier, userID int, exchangeID *int, montant int, typ string) error {
	ret := _mock.Called(ctx, q, userID, exchangeID, montant, typ)

	if len(ret) == 0 {
		panic("no return value specified for AddCreditTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dbx.Querier, int, *int, int, string) error); ok {
		r0 = returnFunc(ctx, q, userID, exchangeID, montant, typ)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_AddCreditTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCreditTransaction'
type MockRepository_AddCreditTransaction_Call struct {
	*mock.Call
}

// AddCreditTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - q dbx.Querier
//   - userID int
//   - exchangeID *int
//   - montant int
//   - typ string
func (_e *MockRepository_Expecter) AddCreditTransaction(ctx any, q any, userID any, exchangeID any, montant any, typ any) *MockRepository_AddCreditTransaction_Call {
	return &MockRepository_AddCreditTransaction_Call{Call: _e.mock.On("AddCreditTransaction", ctx, q, userID, exchangeID, montant, typ)}
}

func (_c *MockRepository_AddCreditTransaction_Call) Run(run func(ctx context.Context, q dbx.Querier, userID int, exchangeID *int, montant int, typ string)) *MockRepository_AddCreditTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dbx.Querier
		if args[1] != nil {
			arg1 = args[1].(dbx.Querier)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *int
		if args[3] != nil {
			arg3 = args[3].(*int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockRepository_AddCreditTransaction_Call) Return(err error) *MockRepository_AddCreditTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_AddCreditTransaction_Call) RunAndReturn(run func(ctx context.Context, q dbx.Querier, userID int, exchangeID *int, montant int, typ string) error) *MockRepository_AddCreditTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, u *user.User) error {
	ret := _mock.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.User) error); ok {
		r0 = returnFunc(ctx, u)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - u *user.User
func (_e *MockRepository_Expecter) Create(ctx any, u any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, u)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, u *user.User)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *user.User
		if args[1] != nil {
			arg1 = args[1].(*user.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(err error) *MockRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, u *user.User) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByID(ctx context.Context, id int) (user.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (user.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) user.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(user.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockRepository_Expecter) GetByID(ctx any, id any) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(user1 user.User, err error) *MockRepository_GetByID_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (user.User, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSkills provides a mock function for the type MockRepository
func (_mock *MockRepository) GetSkills(ctx context.Context, userID int) ([]user.Skill, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetSkills")
	}

	var r0 []user.Skill
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]user.Skill, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []user.Skill); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.Skill)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetSkills_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSkills'
type MockRepository_GetSkills_Call struct {
	*mock.Call
}

// GetSkills is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockRepository_Expecter) GetSkills(ctx any, userID any) *MockRepository_GetSkills_Call {
	return &MockRepository_GetSkills_Call{Call: _e.mock.On("GetSkills", ctx, userID)}
}

func (_c *MockRepository_GetSkills_Call) Run(run func(ctx context.Context, userID int)) *MockRepository_GetSkills_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetSkills_Call) Return(skills []user.Skill, err error) *MockRepository_GetSkills_Call {
	_c.Call.Return(skills, err)
	return _c
}

func (_c *MockRepository_GetSkills_Call) RunAndReturn(run func(ctx context.Context, userID int) ([]user.Skill, error)) *MockRepository_GetSkills_Call {
	_c.Call.Return(run)
	return _c
}

// SetSkills provides a mock function for the type MockRepository
func (_mock *MockRepository) SetSkills(ctx context.Context, userID int, skills []user.Skill) error {
	ret := _mock.Called(ctx, userID, skills)

	if len(ret) == 0 {
		panic("no return value specified for SetSkills")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, []user.Skill) error); ok {
		r0 = returnFunc(ctx, userID, skills)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SetSkills_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSkills'
type MockRepository_SetSkills_Call struct {
	*mock.Call
}

// SetSkills is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - skills []user.Skill
func (_e *MockRepository_Expecter) SetSkills(ctx any, userID any, skills any) *MockRepository_SetSkills_Call {
	return &MockRepository_SetSkills_Call{Call: _e.mock.On("SetSkills", ctx, userID, skills)}
}

func (_c *MockRepository_SetSkills_Call) Run(run func(ctx context.Context, userID int, skills []user.Skill)) *MockRepository_SetSkills_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 []user.Skill
		if args[2] != nil {
			arg2 = args[2].([]user.Skill)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_SetSkills_Call) Return(err error) *MockRepository_SetSkills_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SetSkills_Call) RunAndReturn(run func(ctx context.Context, userID int, skills []user.Skill) error) *MockRepository_SetSkills_Call {
	_c.Call.Return(run)
	return _c
}

// Stats provides a mock function for the type MockRepository
func (_mock *MockRepository) Stats(ctx context.Context, userID int) (user.Stats, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 user.Stats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (user.Stats, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) user.Stats); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(user.Stats)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockRepository_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockRepository_Expecter) Stats(ctx any, userID any) *MockRepository_Stats_Call {
	return &MockRepository_Stats_Call{Call: _e.mock.On("Stats", ctx, userID)}
}

func (_c *MockRepository_Stats_Call) Run(run func(ctx context.Context, userID int)) *MockRepository_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Stats_Call) Return(stats user.Stats, err error) *MockRepository_Stats_Call {
	_c.Call.Return(stats, err)
	return _c
}

func (_c *MockRepository_Stats_Call) RunAndReturn(run func(ctx context.Context, userID int) (user.Stats, error)) *MockRepository_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRepository
func (_mock *MockRepository) Update(ctx context.Context, id int, u *user.User) error {
	ret := _mock.Called(ctx, id, u)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, *user.User) error); ok {
		r0 = returnFunc(ctx, id, u)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - u *user.User
func (_e *MockRepository_Expecter) Update(ctx any, id any, u any) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, u)}
}

func (_c *MockRepository_Update_Call) Run(run func(ctx context.Context, id int, u *user.User)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *user.User
		if args[2] != nil {
			arg2 = args[2].(*user.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(err error) *MockRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(ctx context.Context, id int, u *user.User) error) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
