// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package exchangemocks

import (
	"context"

	"github.com/jadechy/barterswap/internal/dbx"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCreditLedger creates a new instance of MockCreditLedger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreditLedger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreditLedger {
	mock := &MockCreditLedger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCreditLedger is an autogenerated mock type for the CreditLedger type
type MockCreditLedger struct {
	mock.Mock
}

type MockCreditLedger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreditLedger) EXPECT() *MockCreditLedger_Expecter {
	return &MockCreditLedger_Expecter{mock: &_m.Mock}
}

// AddCreditTransaction provides a mock function for the type MockCreditLedger
func (_mock *MockCreditLedger) AddCreditTransaction(ctx context.Context, q dbx.Querier, userID int, exchangeID *int, montant int, typ string) error {
	ret := _mock.Called(ctx, q, userID, exchangeID, montant, typ)

	if len(ret) == 0 {
		panic("no return value specified for AddCreditTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dbx.Querier, int, *int, int, string) error); ok {
		r0 = returnFunc(ctx, q, userID, exchangeID, montant, typ)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCreditLedger_AddCreditTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCreditTransaction'
type MockCreditLedger_AddCreditTransaction_Call struct {
	*mock.Call
}

// AddCreditTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - q dbx.Querier
//   - userID int
//   - exchangeID *int
//   - montant int
//   - typ string
func (_e *MockCreditLedger_Expecter) AddCreditTransaction(ctx any, q any, userID any, exchangeID any, montant any, typ any) *MockCreditLedger_AddCreditTransaction_Call {
	return &MockCreditLedger_AddCreditTransaction_Call{Call: _e.mock.On("AddCreditTransaction", ctx, q, userID, exchangeID, montant, typ)}
}

func (_c *MockCreditLedger_AddCreditTransaction_Call) Run(run func(ctx context.Context, q dbx.Querier, userID int, exchangeID *int, montant int, typ string)) *MockCreditLedger_AddCreditTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dbx.Querier
		if args[1] != nil {
			arg1 = args[1].(dbx.Querier)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *int
		if args[3] != nil {
			arg3 = args[3].(*int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockCreditLedger_AddCreditTransaction_Call) Return(err error) *MockCreditLedger_AddCreditTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCreditLedger_AddCreditTransaction_Call) RunAndReturn(run func(ctx context.Context, q dbx.Querier, userID int, exchangeID *int, montant int, typ string) error) *MockCreditLedger_AddCreditTransaction_Call {
	_c.Call.Return(run)
	return _c
}
