// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package exchangemocks

import (
	"context"

	"github.com/jadechy/barterswap/internal/service"
	mock "github.com/stretchr/testify/mock"
)

// NewMockServiceGetter creates a new instance of MockServiceGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceGetter {
	mock := &MockServiceGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServiceGetter is an autogenerated mock type for the ServiceGetter type
type MockServiceGetter struct {
	mock.Mock
}

type MockServiceGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceGetter) EXPECT() *MockServiceGetter_Expecter {
	return &MockServiceGetter_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockServiceGetter
func (_mock *MockServiceGetter) GetByID(ctx context.Context, id int) (service.Service, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 service.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (service.Service, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) service.Service); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(service.Service)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceGetter_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockServiceGetter_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockServiceGetter_Expecter) GetByID(ctx any, id any) *MockServiceGetter_GetByID_Call {
	return &MockServiceGetter_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockServiceGetter_GetByID_Call) Run(run func(ctx context.Context, id int)) *MockServiceGetter_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceGetter_GetByID_Call) Return(service1 service.Service, err error) *MockServiceGetter_GetByID_Call {
	_c.Call.Return(service1, err)
	return _c
}

func (_c *MockServiceGetter_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (service.Service, error)) *MockServiceGetter_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
