// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package exchangemocks

import (
	"context"

	"github.com/jadechy/barterswap/internal/dbx"
	"github.com/jadechy/barterswap/internal/exchange"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, e *exchange.Exchange) error {
	ret := _mock.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *exchange.Exchange) error); ok {
		r0 = returnFunc(ctx, e)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - e *exchange.Exchange
func (_e *MockRepository_Expecter) Create(ctx any, e any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, e)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, e *exchange.Exchange)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *exchange.Exchange
		if args[1] != nil {
			arg1 = args[1].(*exchange.Exchange)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(err error) *MockRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, e *exchange.Exchange) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByID(ctx context.Context, id int) (exchange.Exchange, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 exchange.Exchange
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (exchange.Exchange, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) exchange.Exchange); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(exchange.Exchange)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockRepository_Expecter) GetByID(ctx any, id any) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(exchange1 exchange.Exchange, err error) *MockRepository_GetByID_Call {
	_c.Call.Return(exchange1, err)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (exchange.Exchange, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// HasActive provides a mock function for the type MockRepository
func (_mock *MockRepository) HasActive(ctx context.Context, serviceID int) (bool, error) {
	ret := _mock.Called(ctx, serviceID)

	if len(ret) == 0 {
		panic("no return value specified for HasActive")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (bool, error)); ok {
		return returnFunc(ctx, serviceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) bool); ok {
		r0 = returnFunc(ctx, serviceID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, serviceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_HasActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasActive'
type MockRepository_HasActive_Call struct {
	*mock.Call
}

// HasActive is a helper method to define mock.On call
//   - ctx context.Context
//   - serviceID int
func (_e *MockRepository_Expecter) HasActive(ctx any, serviceID any) *MockRepository_HasActive_Call {
	return &MockRepository_HasActive_Call{Call: _e.mock.On("HasActive", ctx, serviceID)}
}

func (_c *MockRepository_HasActive_Call) Run(run func(ctx context.Context, serviceID int)) *MockRepository_HasActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_HasActive_Call) Return(b bool, err error) *MockRepository_HasActive_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_HasActive_Call) RunAndReturn(run func(ctx context.Context, serviceID int) (bool, error)) *MockRepository_HasActive_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRepository
func (_mock *MockRepository) List(ctx context.Context, userID int, status string) ([]exchange.Exchange, error) {
	ret := _mock.Called(ctx, userID, status)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []exchange.Exchange
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) ([]exchange.Exchange, error)); ok {
		return returnFunc(ctx, userID, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) []exchange.Exchange); ok {
		r0 = returnFunc(ctx, userID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]exchange.Exchange)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = returnFunc(ctx, userID, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - status string
func (_e *MockRepository_Expecter) List(ctx any, userID any, status any) *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List", ctx, userID, status)}
}

func (_c *MockRepository_List_Call) Run(run func(ctx context.Context, userID int, status string)) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(exchanges []exchange.Exchange, err error) *MockRepository_List_Call {
	_c.Call.Return(exchanges, err)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func(ctx context.Context, userID int, status string) ([]exchange.Exchange, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateStatus(ctx context.Context, q dbx.Querier, id int, status string) error {
	ret := _mock.Called(ctx, q, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dbx.Querier, int, string) error); ok {
		r0 = returnFunc(ctx, q, id, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - q dbx.Querier
//   - id int
//   - status string
func (_e *MockRepository_Expecter) UpdateStatus(ctx any, q any, id any, status any) *MockRepository_UpdateStatus_Call {
	return &MockRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, q, id, status)}
}

func (_c *MockRepository_UpdateStatus_Call) Run(run func(ctx context.Context, q dbx.Querier, id int, status string)) *MockRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dbx.Querier
		if args[1] != nil {
			arg1 = args[1].(dbx.Querier)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateStatus_Call) Return(err error) *MockRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, q dbx.Querier, id int, status string) error) *MockRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
