// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package exchangemocks

import (
	"context"

	"github.com/jadechy/barterswap/internal/user"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserGetter creates a new instance of MockUserGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserGetter {
	mock := &MockUserGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserGetter is an autogenerated mock type for the UserGetter type
type MockUserGetter struct {
	mock.Mock
}

type MockUserGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserGetter) EXPECT() *MockUserGetter_Expecter {
	return &MockUserGetter_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockUserGetter
func (_mock *MockUserGetter) GetByID(ctx context.Context, id int) (user.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (user.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) user.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(user.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserGetter_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserGetter_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockUserGetter_Expecter) GetByID(ctx any, id any) *MockUserGetter_GetByID_Call {
	return &MockUserGetter_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockUserGetter_GetByID_Call) Run(run func(ctx context.Context, id int)) *MockUserGetter_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserGetter_GetByID_Call) Return(user1 user.User, err error) *MockUserGetter_GetByID_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserGetter_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (user.User, error)) *MockUserGetter_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
