// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dbxmocks

import (
	"context"

	"github.com/jadechy/barterswap/internal/dbx"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTxRunner creates a new instance of MockTxRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxRunner {
	mock := &MockTxRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTxRunner is an autogenerated mock type for the TxRunner type
type MockTxRunner struct {
	mock.Mock
}

type MockTxRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTxRunner) EXPECT() *MockTxRunner_Expecter {
	return &MockTxRunner_Expecter{mock: &_m.Mock}
}

// WithTx provides a mock function for the type MockTxRunner
func (_mock *MockTxRunner) WithTx(ctx context.Context, fn func(q dbx.Querier) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(q dbx.Querier) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTxRunner_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockTxRunner_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(q dbx.Querier) error
func (_e *MockTxRunner_Expecter) WithTx(ctx any, fn any) *MockTxRunner_WithTx_Call {
	return &MockTxRunner_WithTx_Call{Call: _e.mock.On("WithTx", ctx, fn)}
}

func (_c *MockTxRunner_WithTx_Call) Run(run func(ctx context.Context, fn func(q dbx.Querier) error)) *MockTxRunner_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(q dbx.Querier) error
		if args[1] != nil {
			arg1 = args[1].(func(q dbx.Querier) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTxRunner_WithTx_Call) Return(err error) *MockTxRunner_WithTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTxRunner_WithTx_Call) RunAndReturn(run func(ctx context.Context, fn func(q dbx.Querier) error) error) *MockTxRunner_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
