// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package reviewmocks

import (
	"context"

	"github.com/jadechy/barterswap/internal/exchange"
	mock "github.com/stretchr/testify/mock"
)

// NewMockExchangeGetter creates a new instance of MockExchangeGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExchangeGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExchangeGetter {
	mock := &MockExchangeGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExchangeGetter is an autogenerated mock type for the ExchangeGetter type
type MockExchangeGetter struct {
	mock.Mock
}

type MockExchangeGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExchangeGetter) EXPECT() *MockExchangeGetter_Expecter {
	return &MockExchangeGetter_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockExchangeGetter
func (_mock *MockExchangeGetter) GetByID(ctx context.Context, id int) (exchange.Exchange, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 exchange.Exchange
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (exchange.Exchange, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) exchange.Exchange); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(exchange.Exchange)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExchangeGetter_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockExchangeGetter_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockExchangeGetter_Expecter) GetByID(ctx any, id any) *MockExchangeGetter_GetByID_Call {
	return &MockExchangeGetter_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockExchangeGetter_GetByID_Call) Run(run func(ctx context.Context, id int)) *MockExchangeGetter_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExchangeGetter_GetByID_Call) Return(exchange1 exchange.Exchange, err error) *MockExchangeGetter_GetByID_Call {
	_c.Call.Return(exchange1, err)
	return _c
}

func (_c *MockExchangeGetter_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (exchange.Exchange, error)) *MockExchangeGetter_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
