// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package reviewmocks

import (
	"context"

	"github.com/jadechy/barterswap/internal/review"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, r *review.Review) error {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *review.Review) error); ok {
		r0 = returnFunc(ctx, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - r *review.Review
func (_e *MockRepository_Expecter) Create(ctx any, r any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, r)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, r *review.Review)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *review.Review
		if args[1] != nil {
			arg1 = args[1].(*review.Review)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(err error) *MockRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, r *review.Review) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByServiceID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByServiceID(ctx context.Context, serviceID int) ([]review.Review, error) {
	ret := _mock.Called(ctx, serviceID)

	if len(ret) == 0 {
		panic("no return value specified for GetByServiceID")
	}

	var r0 []review.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]review.Review, error)); ok {
		return returnFunc(ctx, serviceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []review.Review); ok {
		r0 = returnFunc(ctx, serviceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]review.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, serviceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByServiceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByServiceID'
type MockRepository_GetByServiceID_Call struct {
	*mock.Call
}

// GetByServiceID is a helper method to define mock.On call
//   - ctx context.Context
//   - serviceID int
func (_e *MockRepository_Expecter) GetByServiceID(ctx any, serviceID any) *MockRepository_GetByServiceID_Call {
	return &MockRepository_GetByServiceID_Call{Call: _e.mock.On("GetByServiceID", ctx, serviceID)}
}

func (_c *MockRepository_GetByServiceID_Call) Run(run func(ctx context.Context, serviceID int)) *MockRepository_GetByServiceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetByServiceID_Call) Return(reviews []review.Review, err error) *MockRepository_GetByServiceID_Call {
	_c.Call.Return(reviews, err)
	return _c
}

func (_c *MockRepository_GetByServiceID_Call) RunAndReturn(run func(ctx context.Context, serviceID int) ([]review.Review, error)) *MockRepository_GetByServiceID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByUserID(ctx context.Context, userID int) ([]review.Review, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []review.Review
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]review.Review, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []review.Review); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]review.Review)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockRepository_Expecter) GetByUserID(ctx any, userID any) *MockRepository_GetByUserID_Call {
	return &MockRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID int)) *MockRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetByUserID_Call) Return(reviews []review.Review, err error) *MockRepository_GetByUserID_Call {
	_c.Call.Return(reviews, err)
	return _c
}

func (_c *MockRepository_GetByUserID_Call) RunAndReturn(run func(ctx context.Context, userID int) ([]review.Review, error)) *MockRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// HasReviewed provides a mock function for the type MockRepository
func (_mock *MockRepository) HasReviewed(ctx context.Context, exchangeID int, authorID int) (bool, error) {
	ret := _mock.Called(ctx, exchangeID, authorID)

	if len(ret) == 0 {
		panic("no return value specified for HasReviewed")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) (bool, error)); ok {
		return returnFunc(ctx, exchangeID, authorID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) bool); ok {
		r0 = returnFunc(ctx, exchangeID, authorID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, exchangeID, authorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_HasReviewed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasReviewed'
type MockRepository_HasReviewed_Call struct {
	*mock.Call
}

// HasReviewed is a helper method to define mock.On call
//   - ctx context.Context
//   - exchangeID int
//   - authorID int
func (_e *MockRepository_Expecter) HasReviewed(ctx any, exchangeID any, authorID any) *MockRepository_HasReviewed_Call {
	return &MockRepository_HasReviewed_Call{Call: _e.mock.On("HasReviewed", ctx, exchangeID, authorID)}
}

func (_c *MockRepository_HasReviewed_Call) Run(run func(ctx context.Context, exchangeID int, authorID int)) *MockRepository_HasReviewed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_HasReviewed_Call) Return(b bool, err error) *MockRepository_HasReviewed_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_HasReviewed_Call) RunAndReturn(run func(ctx context.Context, exchangeID int, authorID int) (bool, error)) *MockRepository_HasReviewed_Call {
	_c.Call.Return(run)
	return _c
}
